/* oxlint-disable */
/* eslint-disable */
// @ts-nocheck
// biome-ignore-all lint: auto-generated
// Auto-generated by @vite-env/core (Standard Schema)
// Do not edit manually — re-generated on every dev server start and build
// Tip: for richer types, use defineEnv() with Zod instead of defineStandardEnv()

declare module "virtual:env/client" {
  const env: {
    readonly VITE_API_URL: string;
    readonly VITE_APP_NAME: string;
  };
  export { env };
  export default env;
}

declare module "virtual:env/server" {
  const env: {
    readonly DATABASE_URL: string;
    readonly JWT_SECRET: string;
    readonly VITE_API_URL: string;
    readonly VITE_APP_NAME: string;
  };
  export { env };
  export default env;
}
