import type { EnvDefinition } from '@vite-env/core'
import fs from 'node:fs/promises'
import path from 'node:path'
import process from 'node:process'
import { defineCommand } from 'citty'
import consola from 'consola'
import { z } from 'zod'

export const generateCommand = defineCommand({
  meta: { description: 'Generate .env.example from your env.ts schema' },
  args: {
    config: { type: 'string', default: 'env.ts' },
    output: { type: 'string', default: '.env.example' },
  },
  async run({ args }) {
    const root = process.cwd()
    const configPath = path.resolve(root, args.config)

    let def: EnvDefinition
    try {
      const { loadEnvConfig } = await import('@vite-env/core/config')
      def = await loadEnvConfig(configPath)
    }
    catch (e) {
      consola.error(
        `Could not load env definition file at: ${configPath}\n`
        + `  Create an env.ts file and export default defineEnv({ ... })`,
      )
      if (e instanceof Error)
        consola.error(e.message)
      process.exit(1)
    }

    const lines: string[] = [
      '# Auto-generated by @vite-env/cli — do not edit manually',
      '# Run: npx vite-env generate',
      '',
    ]

    const sections: Array<[string, z.ZodRawShape | undefined]> = [
      ['Client variables (VITE_ prefix — available everywhere)', def.client],
      ['Server-only variables (never sent to browser)', def.server],
    ]

    for (const [heading, shape] of sections) {
      if (!shape || Object.keys(shape).length === 0)
        continue
      lines.push(`# ── ${heading}`)

      for (const [key, schema] of Object.entries(shape)) {
        // Zod v4: ZodRawShape values are $ZodType, cast for instanceof checks
        const s = schema as z.ZodTypeAny
        const hint = buildHint(s)
        const defaultVal = getDefault(s)
        const reqFlag = isRequired(s) ? ' — required' : ''
        lines.push(`# ${key}: ${hint}${reqFlag}`, `${key}=${defaultVal}`, '')
      }
    }

    const output = path.resolve(root, args.output)
    try {
      await fs.writeFile(output, lines.join('\n'), 'utf-8')
    }
    catch (e) {
      consola.error(`Failed to write ${args.output}. Check file permissions.`)
      if (e instanceof Error)
        consola.error(e.message)
      process.exit(1)
    }
    consola.success(`Generated ${args.output}`)
  },
})

export function buildHint(schema: z.ZodTypeAny): string {
  const inner = unwrap(schema)
  if (inner instanceof z.ZodString)
    return 'string'
  if (inner instanceof z.ZodNumber)
    return 'number'
  if (inner instanceof z.ZodBoolean)
    return 'boolean (true | false | 1 | 0)'
  if (inner instanceof z.ZodEnum)
    return `enum: ${(inner.options as string[]).join(' | ')}`
  if (inner instanceof z.ZodPipe)
    return buildHint(inner.def.out as unknown as z.ZodTypeAny)
  return 'string'
}

export function getDefault(schema: z.ZodTypeAny): string {
  if (schema instanceof z.ZodDefault) {
    const val = (schema.def as { defaultValue: unknown }).defaultValue
    return String(typeof val === 'function' ? val() : val)
  }
  return ''
}

function isRequired(schema: z.ZodTypeAny): boolean {
  return !(schema instanceof z.ZodOptional) && !(schema instanceof z.ZodDefault)
}

function unwrap(schema: z.ZodTypeAny): z.ZodTypeAny {
  if (schema instanceof z.ZodOptional)
    return unwrap(schema.unwrap() as unknown as z.ZodTypeAny)
  if (schema instanceof z.ZodDefault)
    return unwrap((schema.def as { innerType: unknown }).innerType as z.ZodTypeAny)
  if (schema instanceof z.ZodPipe)
    return unwrap(schema.def.out as unknown as z.ZodTypeAny)
  return schema
}
