allowBuilds:
  esbuild: true
  simple-git-hooks: true
shellEmulator: true
trustPolicy: no-downgrade
packages:
  - 'packages/*'
  - playground
catalogs:
  dev:
    '@antfu/eslint-config': ^8.0.0
    '@types/node': ^22.15.29
    '@vitest/coverage-v8': ^4.1.2
    citty: ^0.1.6
    consola: ^3.4.2
    eslint: ^10.2.0
    lint-staged: ^16.4.0
    simple-git-hooks: ^2.13.1
    tsdown: ^0.12.5
    typescript: ^6.0.2
    vite: ^8.0.3
    vitest: ^4.1.2
    zod: ^4.0.0
