// @env node
import type { EnvDefinition, StandardEnvDefinition } from './types'
import fs from 'node:fs/promises'
import path from 'node:path'
import { z } from 'zod'

/**
 * Writes vite-env.d.ts for Zod definitions.
 * Uses instanceof checks to infer TypeScript types from Zod schemas.
 */
export async function generateDts(
  def: EnvDefinition,
  root: string,
): Promise<void> {
  const clientFields = zodShapeToTsFields({ ...def.client })
  const serverFields = zodShapeToTsFields({ ...def.server, ...def.client })

  await writeDts(root, clientFields, serverFields)
}

/**
 * Writes vite-env.d.ts for Standard Schema definitions.
 * All fields are typed as `string` — Standard Schema has no runtime type introspection.
 */
export async function generateStandardDts(
  def: StandardEnvDefinition,
  root: string,
): Promise<void> {
  const clientKeys = Object.keys(def.client ?? {})
  const serverKeys = [...Object.keys(def.server ?? {}), ...clientKeys]

  const clientFields = keysToTsFields(clientKeys)
  const serverFields = keysToTsFields(serverKeys)

  await writeDts(root, clientFields, serverFields, '(Standard Schema)')
}

async function writeDts(
  root: string,
  clientFields: string,
  serverFields: string,
  tag = '',
): Promise<void> {
  const header = tag
    ? `// Auto-generated by @vite-env/core ${tag}\n// Do not edit manually — re-generated on every dev server start and build\n// Tip: for richer types, use defineEnv() with Zod instead of defineStandardEnv()`
    : `// Auto-generated by @vite-env/core\n// Do not edit manually — re-generated on every dev server start and build`

  const dts = `${header}

declare module 'virtual:env/client' {
  const env: {
${clientFields}
  }
  export { env }
  export default env
}

declare module 'virtual:env/server' {
  const env: {
${serverFields}
  }
  export { env }
  export default env
}
`

  const filePath = path.join(root, 'vite-env.d.ts')
  try {
    await fs.writeFile(filePath, dts, 'utf-8')
  }
  catch (e) {
    throw new Error(
      `[vite-env] Failed to write vite-env.d.ts to ${root}. Check file permissions.`,
      { cause: e },
    )
  }
}

function keysToTsFields(keys: string[]): string {
  return keys
    .map(key => `    readonly ${key}: string`)
    .join('\n')
}

function zodShapeToTsFields(shape: z.ZodRawShape): string {
  return Object.entries(shape)
    .map(([key, schema]) => {
      const s = schema as z.ZodTypeAny
      const tsType = zodToTs(s)
      const optional = isOptional(s)
      return `    readonly ${key}${optional ? '?' : ''}: ${tsType}`
    })
    .join('\n')
}

function zodToTs(schema: z.ZodTypeAny): string {
  if (schema instanceof z.ZodOptional)
    return zodToTs(schema.unwrap() as unknown as z.ZodTypeAny)
  if (schema instanceof z.ZodDefault)
    return zodToTs(schema.def.innerType as unknown as z.ZodTypeAny)
  if (schema instanceof z.ZodString)
    return 'string'
  if (schema instanceof z.ZodNumber)
    return 'number'
  if (schema instanceof z.ZodBoolean)
    return 'boolean'
  if (schema instanceof z.ZodEnum)
    return (schema.options as string[]).map(o => `'${o}'`).join(' | ')
  if (schema instanceof z.ZodPipe)
    return zodToTs(schema.def.out as unknown as z.ZodTypeAny)
  return 'string'
}

function isOptional(schema: z.ZodTypeAny): boolean {
  return schema instanceof z.ZodOptional
}
