// @env node
import type { EnvDefinition } from './types'
import fs from 'node:fs/promises'
import path from 'node:path'
import { z } from 'zod'

/**
 * Writes vite-env.d.ts to project root.
 * Declares virtual:env/client and virtual:env/server module types.
 * Users never need to manually augment ImportMetaEnv again.
 */
export async function generateDts(
  def: EnvDefinition,
  root: string,
): Promise<void> {
  const clientKeys = {
    ...def.client,
    ...def.shared,
  }
  const serverKeys = {
    ...def.server,
    ...def.client,
    ...def.shared,
  }

  const clientFields = zodShapeToTsFields(clientKeys)
  const serverFields = zodShapeToTsFields(serverKeys)

  const dts = `// Auto-generated by @vite-env/core
// Do not edit manually — re-generated on every dev server start and build

declare module 'virtual:env/client' {
  const env: {
${clientFields}
  }
  export { env }
  export default env
}

declare module 'virtual:env/server' {
  const env: {
${serverFields}
  }
  export { env }
  export default env
}
`

  await fs.writeFile(path.join(root, 'vite-env.d.ts'), dts, 'utf-8')
}

function zodShapeToTsFields(shape: z.ZodRawShape): string {
  return Object.entries(shape)
    .map(([key, schema]) => {
      // Zod v4: ZodRawShape values are $ZodType, cast to ZodTypeAny for instanceof checks
      const s = schema as unknown as z.ZodTypeAny
      const tsType = zodToTs(s)
      const optional = isOptional(s)
      return `    readonly ${key}${optional ? '?' : ''}: ${tsType}`
    })
    .join('\n')
}

function zodToTs(schema: z.ZodTypeAny): string {
  if (schema instanceof z.ZodOptional)
    return zodToTs(schema.unwrap() as unknown as z.ZodTypeAny)
  if (schema instanceof z.ZodDefault)
    return zodToTs(schema.def.innerType as unknown as z.ZodTypeAny)
  if (schema instanceof z.ZodString)
    return 'string'
  if (schema instanceof z.ZodNumber)
    return 'number'
  if (schema instanceof z.ZodBoolean)
    return 'boolean'
  if (schema instanceof z.ZodEnum)
    return (schema.options as string[]).map(o => `'${o}'`).join(' | ')
  if (schema instanceof z.ZodPipe)
    return zodToTs(schema.def.out as unknown as z.ZodTypeAny)
  return 'string'
}

function isOptional(schema: z.ZodTypeAny): boolean {
  return schema instanceof z.ZodOptional || schema instanceof z.ZodDefault
}
