// @env node
import type { EnvDefinition, StandardEnvDefinition } from './types'
import type { z as ZodNs } from 'zod'
import fs from 'node:fs/promises'
import path from 'node:path'

/**
 * Writes vite-env.d.ts for Zod definitions.
 * Uses instanceof checks to infer TypeScript types from Zod schemas.
 * Zod is loaded dynamically so this module can be imported without zod installed.
 */
export async function generateDts(
  def: EnvDefinition,
  root: string,
): Promise<void> {
  const { z } = await import('zod')

  const gatedKeys = gatedPresetKeys(def)
  const clientFields = zodShapeToTsFields(z, { ...def.client }, gatedKeys)
  const serverFields = zodShapeToTsFields(z, { ...def.server, ...def.client }, gatedKeys)

  await writeDts(root, clientFields, serverFields)
}

/**
 * Detection-gated preset keys (not user-overridden) validate as optional
 * off-platform — typing them required would lie during local dev.
 */
function gatedPresetKeys(def: EnvDefinition): Set<string> {
  const keys = new Set<string>()
  for (const preset of def.presets ?? []) {
    if (!preset.detect)
      continue
    for (const side of ['server', 'client'] as const) {
      for (const [key, schema] of Object.entries(preset[side] ?? {})) {
        if (def[side]?.[key] === schema)
          keys.add(key)
      }
    }
  }
  return keys
}

/**
 * Writes vite-env.d.ts for Standard Schema definitions.
 * All fields are typed as `string` — Standard Schema has no runtime type introspection.
 */
export async function generateStandardDts(
  def: StandardEnvDefinition,
  root: string,
): Promise<void> {
  const clientKeys = Object.keys(def.client ?? {})
  const serverKeys = [...Object.keys(def.server ?? {}), ...clientKeys]

  const clientFields = keysToTsFields(clientKeys)
  const serverFields = keysToTsFields(serverKeys)

  await writeDts(root, clientFields, serverFields, '(Standard Schema)')
}

function buildHeader(tag = ''): string {
  const lines = [
    '/* oxlint-disable */',
    '/* eslint-disable */',
    '// @ts-nocheck',
    '// biome-ignore-all lint: auto-generated',
    `// Auto-generated by @vite-env/core${tag ? ` ${tag}` : ''}`,
    '// Do not edit manually — re-generated on every dev server start and build',
  ]
  if (tag) {
    lines.push('// Tip: for richer types, use defineEnv() with Zod instead of defineStandardEnv()')
  }
  return lines.join('\n')
}

async function writeDts(
  root: string,
  clientFields: string,
  serverFields: string,
  tag = '',
): Promise<void> {
  const header = buildHeader(tag)

  const dts = `${header}

declare module 'virtual:env/client' {
  const env: {
${clientFields}
  }
  export { env }
  export default env
}

declare module 'virtual:env/server' {
  const env: {
${serverFields}
  }
  export { env }
  export default env
}
`

  const filePath = path.join(root, 'vite-env.d.ts')
  try {
    await fs.writeFile(filePath, dts, 'utf-8')
  }
  catch (e) {
    throw new Error(
      `[vite-env] Failed to write vite-env.d.ts to ${root}. Check file permissions.`,
      { cause: e },
    )
  }
}

function keysToTsFields(keys: string[]): string {
  return keys
    .map(key => `    readonly ${key}: string`)
    .join('\n')
}

function zodShapeToTsFields(z: typeof ZodNs, shape: Record<string, unknown>, gatedKeys: Set<string>): string {
  return Object.entries(shape)
    .map(([key, schema]) => {
      const tsType = zodToTs(z, schema)
      const optional = schema instanceof z.ZodOptional || gatedKeys.has(key)
      return `    readonly ${key}${optional ? '?' : ''}: ${tsType}`
    })
    .join('\n')
}

function zodToTs(z: typeof ZodNs, schema: unknown): string {
  if (schema instanceof z.ZodOptional)
    return zodToTs(z, schema.unwrap())
  if (schema instanceof z.ZodDefault)
    return zodToTs(z, schema.def.innerType)
  if (schema instanceof z.ZodString)
    return 'string'
  if (schema instanceof z.ZodNumber)
    return 'number'
  if (schema instanceof z.ZodBoolean)
    return 'boolean'
  if (schema instanceof z.ZodEnum)
    return (schema.options as string[]).map(o => `'${o}'`).join(' | ')
  if (schema instanceof z.ZodPipe)
    return zodToTs(z, schema.def.out)
  return 'string'
}
