export type GuardMode = 'error' | 'stub' | 'warn'

export type GuardResult
  = | { allowed: true }
    | { allowed: false, mode: GuardMode, envName: string, importer: string | undefined }

export type GuardFail = Extract<GuardResult, { allowed: false }>

/**
 * Determines whether the given Vite environment is allowed to import virtual:env/server.
 * Returns a GuardResult discriminated union — allowed or fail with context.
 * When this.environment is undefined (should not occur with Vite ≥ 8), callers default
 * envName to 'client' — failing closed (restrictive) is safer than failing open.
 */
export function checkServerModuleAccess(
  envName: string,
  serverEnvironments: string[],
  mode: GuardMode,
  importer: string | undefined,
): GuardResult {
  if (serverEnvironments.includes(envName))
    return { allowed: true }
  return { allowed: false, mode, envName, importer }
}

/**
 * Generates the stub virtual module returned when onClientAccessOfServerModule is 'stub'.
 * The stub throws at runtime if executed — its message reflects that this import was
 * expected to be unreachable and the assumption was wrong.
 */
export function buildServerStubModule(envName: string): { code: string, moduleType: 'js' } {
  return {
    moduleType: 'js',
    code: `// Auto-generated by @vite-env/core — server-only module stub
throw new Error(
  '[vite-env] virtual:env/server was imported in the "${envName}" environment. ' +
  'This module is server-only and was replaced with a stub. ' +
  'To allow this environment: add it to serverEnvironments. ' +
  'To suppress this stub: ensure this import never executes in the "${envName}" environment.'
);`,
  }
}
