// @env node
import type { GuardFail } from './guard'
import fs from 'node:fs/promises'
import path from 'node:path'
import { formatGuardLogEntry } from './format'

const LOG_HEADER = `# vite-env warnings — generated by @vite-env/core
# These warnings will become hard errors in 1.0.0.
# To enforce immediately: ViteEnv({ onClientAccessOfServerModule: 'error' })
# To acknowledge and suppress: ViteEnv({ onClientAccessOfServerModule: 'stub' })
# To allow specific environments: ViteEnv({ serverEnvironments: ['ssr', 'workerd'] })`

/**
 * Writes accumulated GuardFail entries to vite-env-warnings.log in the project root.
 * Overwrites on each build — stale entries from previous builds must not persist.
 * Called only in 'warn' mode from buildEnd, after verifying the build succeeded.
 */
export async function writeWarningsLog(fails: GuardFail[], root: string): Promise<void> {
  const timestamp = new Date().toISOString()
  const entries = fails.map(fail => formatGuardLogEntry(fail, timestamp)).join('\n\n')
  const content = `${LOG_HEADER}\n\n${entries}\n`
  const filePath = path.join(root, 'vite-env-warnings.log')
  try {
    await fs.writeFile(filePath, content, 'utf-8')
  }
  catch (e) {
    throw new Error(
      `[vite-env] Failed to write vite-env-warnings.log to ${root}. Check file permissions.`,
      { cause: e },
    )
  }
}
