import type { AnyEnvDefinition } from './types'

export function buildClientModule(
  def: AnyEnvDefinition,
  data: Record<string, unknown>,
): { code: string, moduleType: 'js' } {
  const clientKeys = new Set(Object.keys(def.client ?? {}))

  const clientData = Object.fromEntries(
    Object.entries(data).filter(([k]) => clientKeys.has(k)),
  )

  return {
    moduleType: 'js', // Required: Vite 8 / Rolldown explicit moduleType
    code: `// Auto-generated by @vite-env/core — do not edit
export const env = Object.freeze(${JSON.stringify(clientData, null, 2)});
export default env;`,
  }
}

export function buildServerModule(
  _def: AnyEnvDefinition,
  data: Record<string, unknown>,
): { code: string, moduleType: 'js' } {
  return {
    moduleType: 'js',
    code: `// Auto-generated by @vite-env/core — do not edit
export const env = Object.freeze(${JSON.stringify(data, null, 2)});
export default env;`,
  }
}
