import type { AnyEnvDefinition } from "./types";

export type ServerRuntimeMode = "build-time" | "process-env";

function getAllKeys(def: AnyEnvDefinition): string[] {
  const serverKeys = Object.keys(def.server ?? {});
  const clientKeys = Object.keys(def.client ?? {});
  return [...new Set([...serverKeys, ...clientKeys])];
}

function buildInlinedModule(data: Record<string, unknown>): { code: string; moduleType: "js" } {
  return {
    moduleType: "js",
    code: `// Auto-generated by @vite-env/core — do not edit
export const env = Object.freeze(${JSON.stringify(data, null, 2)});
export default env;`,
  };
}

export function buildClientModule(
  def: AnyEnvDefinition,
  data: Record<string, unknown>,
): { code: string; moduleType: "js" } {
  const clientKeys = new Set(Object.keys(def.client ?? {}));
  const clientData = Object.fromEntries(Object.entries(data).filter(([k]) => clientKeys.has(k)));
  return buildInlinedModule(clientData);
}

export function buildServerModule(
  def: AnyEnvDefinition,
  data: Record<string, unknown>,
  serverRuntime: ServerRuntimeMode = "build-time",
): { code: string; moduleType: "js" } {
  if (serverRuntime === "process-env") {
    const keys = getAllKeys(def);
    const filteredData = Object.fromEntries(Object.entries(data).filter(([k]) => keys.includes(k)));
    return buildInlinedModule(filteredData);
  }
  return buildInlinedModule(data);
}
