/* oxlint-disable */
/* eslint-disable */
// @ts-nocheck
// biome-ignore-all lint: auto-generated
// Auto-generated by @vite-env/core
// Do not edit manually — re-generated on every dev server start and build

declare module "virtual:env/client" {
  const env: {
    readonly VITE_APP_NAME: string;
  };
  export { env };
  export default env;
}

declare module "virtual:env/server" {
  const env: {
    readonly NETLIFY?: "true";
    readonly BUILD_ID?: string;
    readonly CONTEXT?: "production" | "deploy-preview" | "branch-deploy" | "dev";
    readonly DEPLOY_ID?: string;
    readonly DEPLOY_URL?: string;
    readonly DEPLOY_PRIME_URL?: string;
    readonly URL?: string;
    readonly BRANCH?: string;
    readonly COMMIT_REF?: string;
    readonly PULL_REQUEST?: "true";
    readonly REVIEW_ID?: string;
    readonly REPOSITORY_URL?: string;
    readonly INCOMING_HOOK_TITLE?: string;
    readonly INCOMING_HOOK_URL?: string;
    readonly DATABASE_URL: string;
    readonly VITE_APP_NAME: string;
  };
  export { env };
  export default env;
}
