// Auto-generated by @vite-env/core
// Do not edit manually — re-generated on every dev server start and build

declare module 'virtual:env/client' {
  const env: {
    readonly VITE_API_URL: string
    readonly VITE_APP_NAME: string
    readonly VITE_DEBUG: boolean
    readonly VITE_LOG_LEVEL: 'debug' | 'info' | 'warn' | 'error'
  }
  export { env }
  export default env
}

declare module 'virtual:env/server' {
  const env: {
    readonly DATABASE_URL: string
    readonly JWT_SECRET: string
    readonly DB_POOL_SIZE: number
    readonly REDIS_URL?: string
    readonly VITE_API_URL: string
    readonly VITE_APP_NAME: string
    readonly VITE_DEBUG: boolean
    readonly VITE_LOG_LEVEL: 'debug' | 'info' | 'warn' | 'error'
  }
  export { env }
  export default env
}
