/* oxlint-disable */
/* eslint-disable */
// @ts-nocheck
// biome-ignore-all lint: auto-generated
// Auto-generated by @vite-env/core
// Do not edit manually — re-generated on every dev server start and build

declare module "virtual:env/client" {
  const env: {
    readonly VITE_APP_NAME: string;
  };
  export { env };
  export default env;
}

declare module "virtual:env/server" {
  const env: {
    readonly VERCEL?: "1";
    readonly VERCEL_ENV?: "production" | "preview" | "development";
    readonly VERCEL_URL?: string;
    readonly VERCEL_BRANCH_URL?: string;
    readonly VERCEL_PROJECT_PRODUCTION_URL?: string;
    readonly VERCEL_DEPLOYMENT_ID?: string;
    readonly VERCEL_REGION?: string;
    readonly VERCEL_GIT_PROVIDER?: string;
    readonly VERCEL_GIT_REPO_SLUG?: string;
    readonly VERCEL_GIT_REPO_OWNER?: string;
    readonly VERCEL_GIT_COMMIT_REF?: string;
    readonly VERCEL_GIT_COMMIT_SHA?: string;
    readonly VERCEL_GIT_COMMIT_MESSAGE?: string;
    readonly VERCEL_GIT_COMMIT_AUTHOR_LOGIN?: string;
    readonly VERCEL_GIT_PULL_REQUEST_ID?: string;
    readonly VERCEL_SKEW_PROTECTION_ENABLED?: "1";
    readonly DATABASE_URL: string;
    readonly VITE_APP_NAME: string;
  };
  export { env };
  export default env;
}
