/* oxlint-disable */
/* eslint-disable */
// @ts-nocheck
// biome-ignore-all lint: auto-generated
// Auto-generated by @vite-env/core
// Do not edit manually — re-generated on every dev server start and build

declare module "virtual:env/client" {
  const env: {
    readonly VITE_APP_NAME: string;
  };
  export { env };
  export default env;
}

declare module "virtual:env/server" {
  const env: {
    readonly RAILWAY_ENVIRONMENT_ID?: string;
    readonly RAILWAY_ENVIRONMENT_NAME?: string;
    readonly RAILWAY_SERVICE_ID?: string;
    readonly RAILWAY_SERVICE_NAME?: string;
    readonly RAILWAY_PROJECT_ID?: string;
    readonly RAILWAY_PROJECT_NAME?: string;
    readonly RAILWAY_DEPLOYMENT_ID?: string;
    readonly RAILWAY_REPLICA_ID?: string;
    readonly RAILWAY_GIT_COMMIT_SHA?: string;
    readonly RAILWAY_GIT_BRANCH?: string;
    readonly RAILWAY_GIT_REPO_NAME?: string;
    readonly RAILWAY_GIT_REPO_OWNER?: string;
    readonly RAILWAY_PUBLIC_DOMAIN?: string;
    readonly RAILWAY_PRIVATE_DOMAIN?: string;
    readonly RAILWAY_TCP_PROXY_DOMAIN?: string;
    readonly RAILWAY_TCP_PROXY_PORT?: number;
    readonly DATABASE_URL: string;
    readonly VITE_APP_NAME: string;
  };
  export { env };
  export default env;
}
